name: Test

on:
  push:

permissions:
  contents: read
  
jobs:
  preview_url:
    runs-on: ubuntu-latest
    steps:
      # 1. get last deployment for release tracking branch (rest api)
      - name: Get permalink from last deployment
        uses: actions/github-script@v6
        id: permalink
        with:
          result-encoding: string
          script: |
            const {data: deployments} = await github.rest.repos.listDeployments({
              owner: 'primer', 
              repo: 'react', // TODO make this configurable
              ref: 'changeset-release/main',
              environment: 'github-pages',
              per_page: 1
            })
            
            const {data: deploymentStatuses} = await github.rest.repos.listDeploymentStatuses({
              owner: 'primer',
              repo: 'react', // TODO make this configurable
              deployment_id: deployments[0].id
            });
            
            console.log(deploymentStatuses)
       
            const permalink = deploymentStatuses.find(deployment => deployment.state === 'success').environment_url
            return permalink

      - run: echo "${{steps.permalink.outputs.result}}"
