# This action fetches the last deployment url
# for release branch: changeset-release/main

name: Last documentation permalink
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        default: 'react'
    outputs:
      permalink:
        description: "Link to documentation for the last merged release candidate"
        value: ${{ jobs.get_permalink.outputs.permalink }}
    
permissions:
  contents: read
  
jobs:
  get_permalink:
    runs-on: ubuntu-latest
    outputs:
      permalink: ${{ steps.permalink.outputs.result }}
    steps:
      - name: Get permalink from last deployment
        uses: actions/github-script@v6
        id: permalink
        with:
          result-encoding: string
          script: |
            const {data: deployments} = await github.rest.repos.listDeployments({
              owner: 'primer', 
              repo: '${{ inputs.repo }}',
              ref: 'changeset-release/main',
              environment: 'github-pages',
              per_page: 1
            })
            
            const {data: deploymentStatuses} = await github.rest.repos.listDeploymentStatuses({
              owner: 'primer',
              repo: '${{ inputs.repo }}',
              deployment_id: deployments[0].id
            });
            
            const successfulDeployment = deploymentStatuses.find(deployment => deployment.state === 'success')
            
            if (!successfulDeployment) console.log('Could not find a successful deployment')
       
            const permalink = successfulDeployment.environment_url
            return permalink

      - run: echo "${{ steps.permalink.outputs.result }}"
